---

- name: "create_lxc_playbook 1/3"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "create LXC"
      community.general.proxmox:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        node: "{{ proxmox_node }}"
        clone: 300
        hostname: "{{ item.hostname }}"
        vmid: "{{ item.vmid }}"
        state: present
        pool: 'CESI'
        unprivileged: true
      with_items: "{{ students_list }}"

  vars_files:
    - vars/students.yml
    - vars/proxmox.yml

- name: "create_lxc_playbook 2/3"
  hosts: ns3232007
  gather_facts: no
  tasks:
    - name: "add NIC"
      ansible.builtin.shell: "pct set {{ item.vmid }} -net0 name=net0,bridge=vmbr0,ip={{ item.network_ip }}/24,gw=10.10.0.254,tag=1"
      with_items: "{{ students_list }}"

  vars_files:
    - vars/students.yml

- name: "create_lxc_playbook 3/3"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "start LXC"
      community.general.proxmox:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        state: started
        vmid: "{{ item.vmid }}"
        timeout: 90
        unprivileged: true
      with_items: "{{ students_list }}"

  vars_files:
    - vars/students.yml
    - vars/proxmox.yml
