---

- name: "delete_lxc_playbook"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "stop LXC"
      community.general.proxmox:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        state: stopped
        vmid: "{{ item.vmid }}"
        unprivileged: true
      with_items: "{{ students_list }}"
      ignore_errors: true

    - name: "delete LXC"
      community.general.proxmox:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        state: absent
        vmid: "{{ item.vmid }}"
        unprivileged: true
      with_items: "{{ students_list }}"

  vars_files:
    - vars/students.yml
    - vars/proxmox.yml

