---

- name: "change_password_playbook"
  hosts: all
  tasks:
    - name: "change root password"
      user:
        name: root
        update_password: always
        password: "{{ root_password | password_hash('sha512') }}"

  vars_files:
    vars/password.yml
