---

- name: "change_password_playbook"
  hosts: all
  tasks:
    - name: "change root password"
      user:
        name: root
        update_password: always
        password: "{{ item.password | password_hash('sha512') }}"
      when: item.hostname == inventory_hostname
      with_items: "{{ students_list }}"

  vars_files:
    vars/students.yml
