---

- name: "reboot_lxc_playbook"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "restart LXC"
      community.general.proxmox:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: "{{ proxmox_api_host }}"
        state: restarted
        vmid: "{{ item.vmid }}"
        timeout: 90
        unprivileged: true
      with_items: "{{ students_list }}"

  vars_files:
    - vars/students.yml
    - vars/proxmox.yml
