---

- name: "stop LXC"
  community.general.proxmox:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    state: stopped
    vmid: "201"
    unprivileged: true
    force: true
    timeout: 120
  delegate_to: localhost
  run_once: true
  ignore_errors: true

- name: "delete LXC"
  community.general.proxmox:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    state: absent
    vmid: "201"
    unprivileged: true
  delegate_to: localhost
  run_once: true

- name: "create LXC"
  community.general.proxmox:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ proxmox_node }}"
    clone: 300
    hostname: "hathor"
    vmid: "201"
    state: present
    pool: 'Admin'
    unprivileged: true
  delegate_to: localhost
  run_once: true

- name: "add NIC"
  ansible.builtin.shell: "pct set 201 -net0 name=net0,bridge=vmbr0,ip=10.10.0.11/24,gw=10.10.0.254,tag=1"
  delegate_to: ns3232007
  run_once: true

- name: "inscrease ram"
  ansible.builtin.shell: "pct set 201 -memory 4096"
  delegate_to: ns3232007
  run_once: true

- name: "inscrease swap"
  ansible.builtin.shell: "pct set 201 -swap 4096"
  delegate_to: ns3232007
  run_once: true

- name: "start LXC"
  community.general.proxmox:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    state: started
    vmid: "201"
    timeout: 90
    unprivileged: true
  delegate_to: localhost
  run_once: true

