---

- name: "TP07 Exo 3"
  hosts: all #mathieu.raoux-2,mathieu.raoux-3
  tasks:
    - name: "Create user"
      ansible.builtin.user:
        name: tp0703
        update_password: always
        create_home: yes
        password: "toto | password_hash('sha512')"

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: tp0703
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
      become_user: tp0703
